// Interface for LLM providers — accepts user message, returns LLM response. Implemented by OllamaProvider (Phase 1) and ClaudeProvider (later).
namespace Mira.Core.Interfaces;

public interface ILlmProvider
{
    /// <summary>
    /// Generates a response from the LLM based on the user message.
    /// </summary>
    /// <param name="systemPrompt">The system prompt to guide the LLM's response.</param>
    /// <param name="userMessage">The user's message or query.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>The response generated by the LLM.</returns>
    Task<string> GenerateResponseAsync(string systemPrompt, string userMessage, CancellationToken ct);
}